language: ruby

dist: trusty
sudo: false

before_install:
  - rvm get head
  - gem install bundler

rvm:
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.1.6.0
  - rbx-2.7

gemfile:
  - Gemfile
  - Gemfile-http-0.8
  - Gemfile-http-0.9
  - Gemfile-http-1.0

matrix:
  allow_failures:
  - rvm: rbx-2.7